### PR TITLE
Localize OpenMP thread use and count to the GCs theaded with mini-GS approach

### PR DESCRIPTION
**Pull request by aoloso**
## Types of change(s)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)
- [ ] Refactor (no functional changes, no api changes)

## Checklist
- [X] Tested this change with a run of GEOSgcm
- [ ] Ran the Unit Tests (`make tests`)

## Description
For GWD and GOCART2G threaded with the mini-gridcomp approach, the ability to selectively turn OpenMP off for those components where OpenMP is required for other components is not working as inteneded. The runtime option   `use_threads: .FALSE.` to achieve that is being ignored. A branch called bugfix/aoloso/gridComp_level_numthrds has been created fro MAPL, GEOSgcm_GridComp, and GOCART to resolve this bug.

The affected files are `MAPL.F90, MAPL_Generic.F90, MaplGenericComponent.F90, OpenMP_Support.F90, GOCART2G_GridCompMod.F90, CA2G_GridCompMod.F90, DU2G_GridCompMod.F90, NI2G_GridCompMod.F90, SU2G_GridCompMod.F90 GEOS_GwdGridComp.F90`.

## Related Issue
1411

### CODE REVIEW

**Comment by mathomp4** [comment]
@aoloso I changed the base to be to `develop` as it was changing too many files.

**Comment by aoloso** [comment]
@copilot : What do you think about this PR?

**Comment by mathomp4** [comment]
The CI error is interesting here. The issue is that the other branches for this by @aoloso are based on GEOSgcm v12. But in MAPL, our CI is currently still based on GEOSgcm v11 (since that is what GEOSgcm `main` is). 

So this is failing since it's checking out the "wrong" GEOSgcm_GridComp, say, from https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/1412

**Review by tclune — DISMISSED** [review]

**Comment by mathomp4** [comment]
Okay. I was wrong. This *does* change an interface in a way:

```
/discover/nobackup/mathomp4/SystemTests/builds/AGCM_V12/CURRENT/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSgwd_GridComp/GEOS_GwdGridComp.F90(134): error #6404: This name does not have a type, and must have an explicit type.   [MAPL_GET_NUM_THREADS]
      num_threads = MAPL_get_num_threads()
--------------------^
```

So we might need to coordinate with @sdrabenh

**Comment by tclune** [comment]
@mathomp4 You do it as 3 PRs.   PR1 in MAPL adds the interface.   PR2 changes the client code to use PR1.  PR3 eliminates old interface.

Changes are  small so you can probably use superpowers to merge before waiting on all CI.
