### PR TITLE
Fixes #1360. Fix NAG build bug

### LINKED ISSUE #1360: NAG 7.1 Issue with MAPL develop
So I just tried building MAPL `develop` with NAG 7.1 and it dies in the build with:
```
/Users/mathomp4/Models/MAPL-NAG/MAPL/base/cub2latlon_regridder.F90:349:25: error: operand of type 'struct pfio_attributemod_DT_attribute' where arithmetic or pointer type is required
ppTmp1.addr = (Pointer) *pTmp2;
                        ^~~~~~
1 error generated.
make[2]: *** [base/CMakeFiles/cub2latlon.x.dir/build.make:75: base/CMakeFiles/cub2latlon.x.dir/cub2latlon_regridder.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2342: base/CMakeFiles/cub2latlon.x.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
The line it points to isn't too enlightening to me:

https://github.com/GEOS-ESM/MAPL/blob/73a2cfaa074d821d4f6d87c65b6cd394c851bc04/base/cub2latlon_regridder.F90#L349

but maybe @tclune can figure it out?

(Or maybe I have a bug in my NAG setup, which isn't impossible!)

### PR DESCRIPTION
**Pull request by mathomp4**
## Description

Fixes a build bug with NAG. More of a workaround than a fix I suppose, but it might take @weiyuan-jiang level knowledge to make a reproducer for NAG.

So for now, we implement a fix from @tclune 

## Related Issue

Closes #1360 

## Motivation and Context

Lets MAPL build with NAG 7.1

## How Has This Been Tested?

Built the branch with Intel, GNU, and NAG. All worked.

I'll also build and run with GEOSgcm, but it seems trivial for that (as it only really affects `base/cub2latlon_regridder.F90`. But I'll also tag @bena-nasa on this so he can make sure it's good by him.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (affects only documentation or cleanup)

## Checklist:

- [x] I have tested this change with a run of GEOSgcm (if non-trivial)
- [x] I have added one of the required labels (0 diff, 0 diff trivial, 0 diff structural, non 0-diff)
- [x] I have updated the CHANGELOG.md accordingly following the style of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how)

### CODE REVIEW

**Comment by mathomp4** [comment]
This is zero-diff as expected.
